// <auto-generated />
using System;
using FunctionAppFiapF2.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunctionAppFiapF2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FunctionAppFiapF2.Domain.Estoque", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasColumnType("varchar(4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("CodigoProduto");

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("FunctionAppFiapF2.Domain.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCartaoCredito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProduto");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("FunctionAppFiapF2.Domain.Produto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("FunctionAppFiapF2.Domain.Estoque", b =>
                {
                    b.HasOne("FunctionAppFiapF2.Domain.Produto", "Produto")
                        .WithOne()
                        .HasForeignKey("FunctionAppFiapF2.Domain.Estoque", "CodigoProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("FunctionAppFiapF2.Domain.Pedido", b =>
                {
                    b.HasOne("FunctionAppFiapF2.Domain.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
